---
name: Deploy to Servers

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        machine:
          - hk-hkg
          - us-nyc
          - tw-kskb
          - nl-ams
          - us-sea
          - cn-csx
          - cn-hgh
          - de-fra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup ZeroTier
        run: |
          curl -s https://install.zerotier.com | sudo bash
          sudo zerotier-cli join ${{ secrets.ZEROTIER_ID }}
          sleep 60
          ping ${{ format('v4.{0}.zt.as211390.cloud', matrix.machine) }} -c 10
          ping ${{ format('v6.{0}.zt.as211390.cloud', matrix.machine) }} -c 10
      - name: Copy general configs
        run: python scripts/copy.py ${{ matrix.machine }}
      - name: Upload config files to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avz --delete --inplace'
          REMOTE_HOST: ${{ format('v4.{0}.zt.as211390.cloud', matrix.machine) }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: 22
          SOURCE: bird/${{ matrix.machine }}/
          TARGET: /etc/bird/
      - name: Birdc configure
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            birdc c
            birdc s p
          host: ${{ format('v6.{0}.zt.as211390.cloud', matrix.machine) }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
      - name: Leave ZeroTier
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.ZEROTIER_TOKEN }}" https://api.zerotier.com/api/v1/network/${{ secrets.ZEROTIER_ID }}/member/`sudo zerotier-cli info | awk '{ print $3 }'`
          sudo zerotier-cli leave ${{ secrets.ZEROTIER_ID }}
            