---
name: Deploy to Servers

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        machine:
          - hk-hkg
          - us-nyc
          - au-nsw
          - uk-lon
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy general configs
        run: python scripts/copy.py ${{ matrix.machine }}
      - name: Upload config files to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avz --delete'
          REMOTE_HOST: ${{ format('{0}.nodes.yuzhen.network', matrix.machine) }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: bird/${{ matrix.machine }}/
          TARGET: /etc/bird/
      - name: Birdc configure
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ format('{0}.nodes.yuzhen.network', matrix.machine) }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            birdc c
            birdc s p
            